name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - name: Create a tar archive
        run: |
          cd ..
          tar --exclude=.git* --exclude=node_modules/* --exclude=src/* -czvf notification-service.tar.gz notification-service
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Copy package to S3
        run: |
          aws s3 cp ../notification-service.tar.gz s3://permanent-repos/dev/notification-service.tar.gz
          aws s3 cp ../notification-service.tar.gz s3://permanent-repos/staging/notification-service.tar.gz
          aws s3 cp ../notification-service.tar.gz s3://permanent-repos/prod/notification-service.tar.gz
